@startuml
left to right direction

actor User

rectangle "Recipe App" {
    User --> (Перегляд списку страв)
    User --> (Перегляд рецепта страви)
    User --> (Додавання нової страви)
    User --> (Редагування страви)
    User --> (Видалення страви)
    User --> (Додавання нової колекції)
    User --> (Редагування колекції)
    User --> (Видалення колекції)
    User --> (Формування списку покупок)
    User --> (Перегляд списку покупок)
    User --> (Відзначення придбаного інгредієнта)
    User --> (Інтеграція з ChatGPT)
}
@enduml
